services:
  - type: web
    name: heartDiseasePredictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/gcp-key.json
secretFiles:
      - name: /etc/secrets/gcp-key.json
        path: gcp-key.json